"""Regenerate the examples/ HTML and Markdown outputs with a live LLM.

Runs the hybrid pipeline ONCE per input document (the expensive part —
Surya detection + per-box LLM OCR) and then writes every output format
that derives from that document from the single captured OCR result, so
LM Studio is not hit twice for an HTML + Markdown pair.

Uses the documented example-generation recipe: per-box OCR everywhere
(``dense_mode="always"``), concurrency 5, DPI 200 — see the README's
"Best alignment" note.

Not regenerated by this script:

* ``output_*_grounded.*`` — needs a grounding-capable VLM (e.g.
  ``qwen/qwen3-vl-8b``) served locally; run ``main.py --grounded``
  manually when one is loaded.
* ``output_*.pdf`` — sandwich-PDF outputs come from ``PDFHandler``;
  regenerate via ``main.py`` when the PDF writer changes.

Usage:
    uv run scripts/regen_examples.py                 # writes into examples/
    uv run scripts/regen_examples.py --out-dir tmp/  # stage elsewhere first
    uv run scripts/regen_examples.py --api-base http://localhost:1234/v1 \
        --model allenai/olmocr-2-7b

After regenerating, validate with:
    uv run scripts/check_examples_freshness.py [out-dir]
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
import time
from pathlib import Path

os.environ.setdefault("TQDM_DISABLE", "1")
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

REPO = Path(__file__).resolve().parents[1]
EXAMPLES = REPO / "examples"

# (input file, [(writer-factory kwargs, output name), ...]) — writers are
# built lazily so the heavy imports stay behind the argparse fast path.
JOBS: list[tuple[str, list[tuple[str, dict, str]]]] = [
    ("digital.pdf", [
        ("html", {}, "output_digital.html"),
        ("html", {"invert_dark": True}, "output_digital_invert_dark.html"),
        ("md", {}, "output_digital.md"),
    ]),
    ("handwritten.pdf", [
        ("html", {}, "output_handwritten.html"),
        ("md", {}, "output_handwritten.md"),
    ]),
    ("hybrid.pdf", [
        ("html", {}, "output_hybrid.html"),
        ("md", {}, "output_hybrid.md"),
    ]),
    ("image.png", [
        ("html", {}, "output_image.html"),
        ("md", {}, "output_image.md"),
    ]),
    ("multipage.pdf", [
        ("html", {}, "output_multipage.html"),
    ]),
]


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--out-dir", default=str(EXAMPLES),
                   help="directory to write outputs into (default: examples/)")
    p.add_argument("--api-base", default="http://localhost:1234/v1")
    p.add_argument("--model", default="allenai/olmocr-2-7b",
                   help="OCR model (explicit default — .env may point at a "
                        "non-OCR chat model)")
    p.add_argument("--concurrency", type=int, default=5)
    p.add_argument("--dpi", type=int, default=200)
    return p


async def amain(args: argparse.Namespace) -> int:
    from pdf_ocr import HybridAligner, OCRPipeline, OCRProcessor, PDFHandler
    from pdf_ocr.core.html import HTMLHandler
    from pdf_ocr.core.markdown import MarkdownHandler

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    ocr = OCRProcessor(api_base=args.api_base, model=args.model)
    await ocr.ensure_model_loaded()
    print(f"model {args.model} confirmed at {args.api_base}")

    aligner = HybridAligner()  # loads Surya once for all documents
    pdf_handler = PDFHandler()

    def make_writer(kind: str, kwargs: dict):
        return HTMLHandler(**kwargs) if kind == "html" else MarkdownHandler(**kwargs)

    for input_name, outputs in JOBS:
        input_path = str(EXAMPLES / input_name)
        captured: dict = {}

        def capture(inp, outp, pages_data, dpi):
            captured["pages_data"] = pages_data
            captured["dpi"] = dpi

        pipeline = OCRPipeline(
            aligner=aligner, ocr_processor=ocr,
            pdf_handler=pdf_handler, output_writer=capture,
        )
        t0 = time.perf_counter()
        await pipeline.run(
            input_path, str(out_dir / "_capture.ignore"),
            dpi=args.dpi, concurrency=args.concurrency, dense_mode="always",
        )
        n_boxes = sum(len(v) for v in captured["pages_data"].values())
        print(f"{input_name}: OCR done in {time.perf_counter() - t0:.1f}s "
              f"({n_boxes} boxes)")

        for kind, kwargs, name in outputs:
            make_writer(kind, kwargs).embed_structured_text(
                input_path, str(out_dir / name),
                captured["pages_data"], dpi=captured["dpi"],
            )
            print(f"  wrote {name}")
    return 0


def main() -> int:
    return asyncio.run(amain(build_parser().parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
